apiVersion: v1
kind: Secret
metadata:
  name: vm-launcher-sa-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: vm-launcher-sa
type: kubernetes.io/service-account-token
